name: Pytest Bonus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-lib.txt
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
